import type { Tool } from './types'

export const toolsData: Tool[] = [
  {
    category: `Ad Campaign Optimization`,
    vendor: `Adriel`,
    description: `Monitors and auto-adjusts ad performance strategies.`,
    link: `https://www.adriel.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.adriel.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Ad Campaign Optimization`,
    vendor: `Morphio`,
    description: `Analyzes ad performance and provides recommendations.`,
    link: `https://www.morphio.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.morphio.ai`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Ad Campaign Optimization`,
    vendor: `Neuraltext`,
    description: `Combines SEO and advertising to create optimized ad copy.`,
    link: `https://www.neuraltext.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $19`, price: `See site` }, { tier: `mo | $119`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `AEO`,
    vendor: `Peec ai`,
    description: `Analytics platform that helps marketers monitor and optimize brand visibility within generative AI search and large language models.`,
    link: `https://www.peec.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.peec.ai`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AEO`,
    vendor: `Profound`,
    description: `AI visibility and content optimization platform that helps brands understand, improve, and measure how they appear in AI-powered search results.`,
    link: `https://www.profound.so`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.profound.so`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AI automation platform`,
    vendor: `Canva`,
    description: `Design platform with AI-powered design suggestions.`,
    link: `https://www.canva.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $15`, price: `See site` }, { tier: `mo | $10`, price: `See site` }, { tier: `user`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `AI automation platform`,
    vendor: `Gumloop`,
    description: `No-code automation platform for creating AI-powered workflows.`,
    link: `https://gumloop.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `gumloop.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Aomni`,
    description: `AI-powered prospecting and research platform for B2B sales teams.`,
    link: `https://www.aomni.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.aomni.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Apollo`,
    description: `Sales intelligence and engagement platform with AI-powered insights.`,
    link: `https://www.apollo.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $49`, price: `See site` }, { tier: `mo | $79`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Attention`,
    description: `AI-powered conversation intelligence for sales teams.`,
    link: `https://www.attention.tech`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.attention.tech`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Avoma`,
    description: `AI meeting assistant and conversation intelligence platform.`,
    link: `https://www.avoma.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $19`, price: `See site` }, { tier: `mo | $59`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Clay`,
    description: `Data enrichment and outreach automation platform`,
    link: `https://clay.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `clay.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Common Room`,
    description: `Community intelligence and engagement platform`,
    link: `https://www.commonroom.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.commonroom.io`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Granola`,
    description: `AI-powered meeting notes and CRM.`,
    link: `https://granola.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Momentum`,
    description: `AI-powered sales automation and pipeline management.`,
    link: `https://momentum.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Ocatve HQ`,
    description: `Sales engagement platform.`,
    link: `https://octave.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Persana AI`,
    description: `AI-powered sales prospecting and outreach tool`,
    link: `https://persana.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `persana.ai`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Pocus`,
    description: `Product-led sales platform for revenue teams`,
    link: `https://pocus.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `pocus.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `TableFlow`,
    description: `Data pipeline platform for sales and marketing teams.`,
    link: `https://tableflow.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `AI Sales & Engagement`,
    vendor: `Winn.AI`,
    description: `AI sales assistant for tracking and managing sales conversations.`,
    link: `https://winn.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `AI video`,
    vendor: `HeyGen`,
    description: `AI-powered video creation platform with virtual avatars.`,
    link: `https://www.heygen.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $24`, price: `See site` }, { tier: `mo | $120`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `AI CRM`,
    vendor: `HubSpot`,
    description: `All-in-one marketing platform with AI features.`,
    link: `https://www.hubspot.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $45`, price: `See site` }, { tier: `mo | Custom`, price: `See site` }],
  },
  {
    category: `AI Analytics`,
    vendor: `Grain`,
    description: `AI-powered conversation analytics and insights platform.`,
    link: `https://www.grain.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $19`, price: `See site` }, { tier: `mo | $39`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Communication & Outreach`,
    vendor: `Glyphic`,
    description: `AI-powered sales conversation analytics.`,
    link: `https://glyphic.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `Communication & Outreach`,
    vendor: `Lemlist`,
    description: `Email outreach and automation platform.`,
    link: `https://lemlist.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `$69`, price: `See site` }, { tier: `mo | $99`, price: `See site` }, { tier: `mo | Custom`, price: `See site` }],
  },
  {
    category: `Communication & Outreach`,
    vendor: `Tribble`,
    description: `Social selling automation tool.`,
    link: `https://tribble.so`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `Communication & Outreach`,
    vendor: `Unify`,
    description: `Unified communication platform for sales teams.`,
    link: `https://unify.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `Content Creation`,
    vendor: `ContentBot`,
    description: `AI content generation tool for various marketing materials.`,
    link: `https://contentbot.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $29`, price: `See site` }, { tier: `mo | $59`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Content Creation`,
    vendor: `Copy.ai`,
    description: `AI-powered copywriting and content generation.`,
    link: `https://www.copy.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $49`, price: `See site` }, { tier: `mo | $249`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Content Creation`,
    vendor: `Jasper`,
    description: `AI writing assistant for marketing content.`,
    link: `https://www.jasper.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `$59`, price: `See site` }, { tier: `mo | $125`, price: `See site` }, { tier: `mo | Custom`, price: `See site` }],
  },
  {
    category: `Content Creation`,
    vendor: `Scalenut`,
    description: `AI-powered content research and writing platform.`,
    link: `https://www.scalenut.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $20`, price: `See site` }, { tier: `mo | $75`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Content Creation`,
    vendor: `Wordtune`,
    description: `AI writing companion for improving and rewriting text.`,
    link: `https://www.wordtune.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $9.99`, price: `See site` }, { tier: `mo | $14.99`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Content Creation`,
    vendor: `Writesonic`,
    description: `AI writing tool for various content types.`,
    link: `https://writesonic.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $49`, price: `See site` }, { tier: `mo | $499`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Customer Experience & Personalization`,
    vendor: `Humantic`,
    description: `AI-powered personality insights for better customer interactions.`,
    link: `https://humantic.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `Customer Experience & Personalization`,
    vendor: `Levity`,
    description: `No-code AI platform for automating workflows.`,
    link: `https://levity.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $240`, price: `See site` }, { tier: `mo | Custom`, price: `See site` }],
  },
  {
    category: `Customer Experience & Personalization`,
    vendor: `Outplay`,
    description: `Sales engagement platform with AI-powered sequences.`,
    link: `https://outplayhq.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $79`, price: `See site` }, { tier: `mo | $149`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Customer Experience & Personalization`,
    vendor: `People.ai`,
    description: `AI-powered revenue intelligence platform.`,
    link: `https://people.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `people.ai`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Customer Experience & Personalization`,
    vendor: `Smartly`,
    description: `AI-powered advertising automation platform.`,
    link: `https://www.smartly.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.smartly.io`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Data Intelligence`,
    vendor: `Clearbit Hubspot`,
    description: `Customer intelligence platform for B2B companies.`,
    link: `https://clearbit.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `clearbit.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Data Intelligence`,
    vendor: `Lusha`,
    description: `Contact and company information tool.`,
    link: `https://www.lusha.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $29`, price: `See site` }, { tier: `mo | $51`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Data Intelligence`,
    vendor: `People data labs`,
    description: `Person and company data API for developers.`,
    link: `https://www.peopledatalabs.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.peopledatalabs.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Data Intelligence`,
    vendor: `Salesintel`,
    description: `Human-verified B2B contact and company database.`,
    link: `https://salesintel.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `salesintel.io`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Data Intelligence`,
    vendor: `Scalestack`,
    description: `Data infrastructure platform for scaling operations.`,
    link: `https://scalestack.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `Data Intelligence`,
    vendor: `Zoominfo`,
    description: `B2B contact and company database.`,
    link: `https://www.zoominfo.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.zoominfo.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Data Analytics & Insights`,
    vendor: `Hightouch`,
    description: `Customer data platform with AI-powered insights.`,
    link: `https://www.hightouch.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $300`, price: `See site` }, { tier: `mo | Custom`, price: `See site` }],
  },
  {
    category: `Data Analytics & Insights`,
    vendor: `Octolis`,
    description: `Customer data platform for creating unified customer profiles.`,
    link: `https://octolis.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `octolis.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Data Analytics & Insights`,
    vendor: `Supermetrics`,
    description: `Data integration platform for marketing analytics.`,
    link: `https://supermetrics.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $99`, price: `See site` }, { tier: `mo | $599`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Marketing Automation`,
    vendor: `ActiveCampaign`,
    description: `Email marketing and automation platform.`,
    link: `https://www.activecampaign.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `$15`, price: `See site` }, { tier: `mo | $70`, price: `See site` }, { tier: `mo | $187`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Marketing Automation`,
    vendor: `Autopilot`,
    description: `Marketing automation platform with AI-powered journeys.`,
    link: `https://www.autopilothq.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $49`, price: `See site` }, { tier: `mo | $149`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Marketing Automation`,
    vendor: `Encharge`,
    description: `Behavior-based email marketing automation platform.`,
    link: `https://www.encharge.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $99`, price: `See site` }, { tier: `mo | $699`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Marketing Automation`,
    vendor: `Phantombuster`,
    description: `Cloud-based automation platform for lead generation and outreach.`,
    link: `https://phantombuster.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $56`, price: `See site` }, { tier: `mo | $189`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Marketing Automation`,
    vendor: `Usergems`,
    description: `AI-powered platform for tracking job changes and warm introductions.`,
    link: `https://www.usergems.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.usergems.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Productivity AI`,
    vendor: `Motion`,
    description: `AI-powered calendar and task management.`,
    link: `https://usemotion.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `$19`, price: `See site` }, { tier: `mo | $34`, price: `See site` }, { tier: `mo | Custom`, price: `See site` }],
  },
  {
    category: `SEO Optimization`,
    vendor: `Frase`,
    description: `AI-powered content optimization tool for SEO.`,
    link: `https://www.frase.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $12.66`, price: `See site` }, { tier: `mo | $32.66`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `SEO Optimization`,
    vendor: `Neuronwriter`,
    description: `AI content editor with SEO optimization.`,
    link: `https://neuronwriter.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $23`, price: `See site` }, { tier: `mo | $57`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `SEO Optimization`,
    vendor: `Surferseo`,
    description: `SEO content optimization and research tool.`,
    link: `https://surferseo.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $69`, price: `See site` }, { tier: `mo | $149`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Social Media Management`,
    vendor: `Lately`,
    description: `AI-powered social media content generation and scheduling.`,
    link: `https://www.lately.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $49`, price: `See site` }, { tier: `mo | $149`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Social Media Management`,
    vendor: `Ocoya`,
    description: `AI social media management and content creation platform.`,
    link: `https://www.ocoya.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $15`, price: `See site` }, { tier: `mo | $39`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Social Media Management`,
    vendor: `Socialbee`,
    description: `Social media management platform with AI content suggestions.`,
    link: `https://socialbee.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $29`, price: `See site` }, { tier: `mo | $99`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Social Media Management`,
    vendor: `Vistasocial`,
    description: `Social media management and analytics platform.`,
    link: `https://vistasocial.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $25`, price: `See site` }, { tier: `mo | $65`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Video & Visual Content Creation`,
    vendor: `Pictory`,
    description: `AI-powered video creation from text and scripts.`,
    link: `https://pictory.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $19`, price: `See site` }, { tier: `mo | $39`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Video & Visual Content Creation`,
    vendor: `Runwayml`,
    description: `AI-powered creative tools for video and image generation.`,
    link: `https://runwayml.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $12`, price: `See site` }, { tier: `mo | $28`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Video & Visual Content Creation`,
    vendor: `Synthesia`,
    description: `AI video generation platform with virtual presenters.`,
    link: `https://www.synthesia.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $22`, price: `See site` }, { tier: `mo | $67`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Video & Visual Content Creation`,
    vendor: `Veed`,
    description: `Online video editing platform with AI-powered features.`,
    link: `https://www.veed.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $12`, price: `See site` }, { tier: `mo | $24`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Cargo`,
    description: `No-code automation platform for data workflows.`,
    link: `https://www.cargo.site`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.cargo.site`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Wiza`,
    description: `LinkedIn lead generation and contact export tool.`,
    link: `https://wiza.co`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $30`, price: `See site` }, { tier: `mo | $60`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Automation Anywhere`,
    description: `Enterprise robotic process automation platform.`,
    link: `https://www.automationanywhere.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `See pricing > https:`, price: `See site` }, { tier: `www.automationanywhere.com`, price: `See site` }, { tier: `pricing`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Captain Data`,
    description: `Data extraction and automation platform.`,
    link: `https://captaindata.co`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Integrately`,
    description: `Integration platform for automating workflows between apps.`,
    link: `https://integrately.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $15.83`, price: `See site` }, { tier: `mo | $41.58`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Make`,
    description: `Visual automation platform (formerly Integromat).`,
    link: `https://make.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $9`, price: `See site` }, { tier: `mo | $16`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `n8n`,
    description: `Open-source workflow automation tool.`,
    link: `https://n8n.io`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $20`, price: `See site` }, { tier: `mo | Custom`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Pabbly`,
    description: `Lifetime deal automation platform.`,
    link: `https://pabbly.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $19`, price: `See site` }, { tier: `mo | $79`, price: `See site` }, { tier: `mo`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `relay.app`,
    description: `Human-in-the-loop automation platform.`,
    link: `https://relay.app`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Relevance ai`,
    description: `AI automation platform for building AI agents.`,
    link: `https://relevance.ai`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `nan`, price: `See site` }],
  },
  {
    category: `Workflow Automation`,
    vendor: `Zapier`,
    description: `Connects apps and automates workflows.`,
    link: `https://zapier.com`,
    reviews: { count: 0, average: 0.0 },
    pricing: [{ tier: `Free | $19.99`, price: `See site` }, { tier: `mo | $399`, price: `See site` }, { tier: `mo`, price: `See site` }],
  }
];
